package:
  name: obscureridge
  version: "0.0.6"

source:
  git_rev: v0.0.6
  git_url: https://github.com/pythonflaskserverapps/obscureridge.git

requirements:
  build:
    - python
    - setuptools
  run:
    

test:
  imports:
    - obscureridge

about:
  home: https://github.com/pythonflaskserverapps/obscureridge
  license: MIT
  license_file: LICENSE
